# File     : Makefile
# Purpose  : makefile for poly 0.0 subdir

# General make settings

export SH = /bin/bash
export MAKEFLAGS += --no-print-directory

# Rules

test :
	@./test.sh

build_ref :
	@:

.PHONY: test build_ref
